### ISSUE TITLE
Add option to customize prompt symbol

### ISSUE THREAD

**Issue by tdeekens** [reobin/typewritten#10]
Thanks for this great theme. I really enjoy it!

I was wondering if supporting a prompt symbol would be something worthwhile. Pure suppots it via a PURE_PROMPT_SYMBOL and we could have a TYPEWRITTEN_PROMPT_SYMBOL.

What do you think?

**Comment by reobin** [comment]
Hi @tdeekens !

This seems reasonable enough to me, and should be pretty easy to implement. I will work on it today.

Thank you for your suggestion!
Robin

**Comment by reobin** [comment]
@all-contributors please add @tdeekens for ideas

**Comment by reobin** [comment]
@all-contributors please add tdeekens for ideas
