### ISSUE TITLE
document zinit install

### ISSUE THREAD

**Issue by xenoterracide** [reobin/typewritten#105]
So I wrote this, and I think it's right, but I'm not entirely certain

```sh
zinit ice wait'!' lucid nocd atload'!tw_setup'$
zinit load reobin/typewritten$
```
The [zinit docs](http://zdharma.org/zinit/wiki/INTRODUCTION/#turbo-load) say

> The exclamation mark in atload'!…' is to track the functions allowing the plugin to be unloaded

hoping you can clarify if I'm doing the right thing.

**Comment by reobin** [comment]
Hi @xenoterracide !

Sorry for taking so long, I have been busy with personal stuff. I am not quite getting what this issue is about. Could you give me more info?

**Comment by xenoterracide** [comment]
hah, I think it was just a question, I believe I've long solved it.
