### ISSUE TITLE
bug: Disabling relative path does not work

### ISSUE THREAD

**Issue by reobin** [reobin/typewritten#106]
As mentioned in #104, there seems to be a problem with the `TYPEWRITTEN_RELATIVE_PATH` option.

**Comment by reobin** [comment]
Hi @CrystalJewell! can you help me feed this issue with more information?

**Comment by CrystalJewell** [comment]
@reobin Sorry I have been crazy busy this week.  I'm circling back to this today.  I'll get screenshots and detail what I'm seeing ASAP.  The TL:DR is that it appears that `TYPEWRITTEN_RELATIVE_PATH="off"` is hitting `TYPEWRITTEN_RELATIVE_PATH="home"` instead.

**Comment by CrystalJewell** [comment]
It appears that `pure` is ignoring the `TYPEWRITTEN_RELATIVE_PATH` variable altogether.

<details>
<summary>TYPEWRITTEN_PROMPT_LAYOUT="pure"</summary>
<br>
<details>
<summary>No Relative path export</summary>

<img width="1220" alt="Screen Shot 2021-02-19 at 1 51 14 PM" src="https://user-images.githubusercontent.com/21298255/108549862-bf5e2100-72bb-11eb-928c-7b2b58f51a2e.png">

</details>

<details>
<summary>TYPEWRITTEN_RELATIVE_PATH="off"</summary>

<img width="1220" alt="Screen Shot 2021-02-19 at 1 52 23 PM" src="https://user-images.githubusercontent.com/21298255/108550002-ef0d2900-72bb-11eb-9d9f-9f6c7f0e90ee.png">

</details>

<details>
<summary>TYPEWRITTEN_RELATIVE_PATH="git"</summary>

<img width="1220" alt="Screen Shot 2021-02-19 at 1 53 30 PM" src="https://user-images.githubusercontent.com/21298255/108550055-03512600-72bc-11eb-8e47-5d48869c7434.png">

</details>

<details>
<summary>TYPEWRITTEN_RELATIVE_PATH="home"</summary>

<img width="1220" alt="Screen Shot 2021-02-19 at 1 54 43 PM" src="https://user-images.githubusercontent.com/21298255/108550089-1237d880-72bc-11eb-9e0c-f0d05dd4b384.png">

</details>

<details>
<summary>TYPEWRITTEN_RELATIVE_PATH="adaptave"</summary>

<img width="1220" alt="Screen Shot 2021-02-19 at 1 52 23 PM" src="https://user-images.githubusercontent.com/21298255/108550002-ef0d2900-72bb-11eb-9d9f-9f6c7f0e90ee.png">

</details>
</details>

<details>
<summary>TYPEWRITTEN_PROMPT_LAYOUT="half-pure"</summary>
<br>
<details>
<summary>No Relative path export</summary>

<img width="1680" alt="Screen Shot 2021-02-19 at 1 59 02 PM" src="https://user-images.githubusercontent.com/21298255/108550760-fd0f7980-72bc-11eb-95e3-363a0c496d4d.png">

</details>

<details>
<summary>TYPEWRITTEN_RELATIVE_PATH="off"</summary>

<img width="1680" alt="Screen Shot 2021-02-19 at 2 00 25 PM" src="https://user-images.githubusercontent.com/21298255/108551032-524b8b00-72bd-11eb-9ca1-70bf7ff9c734.png">

</details>
</details>

<details>
<summary>TYPEWRITTEN_PROMPT_LAYOUT="singleline" & TYPEWRITTEN_RELATIVE_PATH="off"</summary>

<img width="1679" alt="Screen Shot 2021-02-19 at 2 02 27 PM" src="https://user-images.githubusercontent.com/21298255/108551174-8fb01880-72bd-11eb-99a1-690bd4aa7fd1.png">

</details>

<details>
<summary>TYPEWRITTEN_PROMPT_LAYOUT="singleline_verbose" & TYPEWRITTEN_RELATIVE_PATH="off"</summary>

<img width="1680" alt="Screen Shot 2021-02-19 at 2 03 44 PM" src="https://user-images.githubusercontent.com/21298255/108551227-a5bdd900-72bd-11eb-8f52-b13ac5924e43.png">

</details>

<details>
<summary>TYPEWRITTEN_PROMPT_LAYOUT="multiline" & TYPEWRITTEN_RELATIVE_PATH="off"</summary>

<img width="1680" alt="Screen Shot 2021-02-19 at 2 04 38 PM" src="https://user-images.githubusercontent.com/21298255/108551291-ba9a6c80-72bd-11eb-98f5-209774feae24.png">

</details>

**Comment by reobin** [comment]
Thank you for the updates @CrystalJewell !

That was a design decision, actually. Sorry for the confusion! The original Pure prompt displays the whole path that is relative to home. Since the `pure` layout of typewritten is inspired by the original Pure, I made it ignore `TYPEWRITTEN_RELATIVE_PATH` variable.

Now that I think about it, there is no reason for it to do that. It would be a nice and easy feature to add to typewritten.

I'll add the feature request in another issue and close this one.

Thank you @CrystalJewell !
