### ISSUE TITLE
Terminal rendered dummy with noclobber set

### ISSUE THREAD

**Issue by jeevatattva** [reobin/typewritten#115]
**Describe the bug**
I using `zimfw`, which has `NOCLOBBER` set. After installation, when restart shell, I get a warning,

`async_start_worker:38: can't clobber parameter errfd containing file descriptor 0`

Thereafter, unable to use the terminal with various editors.

OS: macOS Catalina 10.15.7
ZSH_VERSION: 5.7.1
ZIMFW: 1.4.3

**To Reproduce**
1. `set -o noclobber` in `.zshrc`
2. start/restart shell
3. `mg <file>`, editor I use.
    `panic: standard input and output must be a terminal`

**Expected behavior**
I should be able to edit the file.

**Solution**
Update `zsh-async`, the fix is present in https://github.com/mafredri/zsh-async/commit/c7f35ecd5b78a990303e3699543a4bc0bfaaa047

**Comment by reobin** [comment]
Hey @jeevatattva !

Thank you so much for opening this issue and suggesting a solution

I opened a PR #116 in which I upgraded async.zsh to 1.8.5. Would you test that on your machine to make sure it works?

If you're not sure how to install locally the PR's version, an easy way to do it is with `npm`:

1. Clone the repository
2. Checkout the `build/update-async-zsh` branch
3. Run `npm install -g .`
4. Restart terminal

**Comment by jeevatattva** [comment]
Removed the theme, installed through `zim`, followed your instructions to set it up again. Now, after restarting the terminal, it is fully functional.

**Comment by reobin** [comment]
Awesome @jeevatattva thank you for your help 🎉

@all-contributors please add @jeevatattva for bug and idea
