### ISSUE TITLE
Visual bug when using completion

### ISSUE THREAD

**Issue by Hello-Helo** [reobin/typewritten#118]
**Describe the bug**
When using tab completion on commands like `cd` when there is 2 options or more, there is a visual bug so that the command shows like `cdcd`. This happens with other commands as well, `mkdir` becomes `mkmkdir`. The command run as normal.
Since i don't a plugin manager for zsh, i could quickly comment lines of all the other features (like syntax highligh) and verify that this only happens with the prompt enable.

**To Reproduce**
1. Enable completion with `autoload -Uz compinit && compinit`
2. Install Typewritten manualy as the guide says 
3. Use completion when there is 2 or more options
4. See the visual bug

**Expected behavior**
No visual bug

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty (it also happens on the tty so I don't think is related)
 - ZSH Version : 5.8

Edit: add tty information

**Comment by reobin** [comment]
Hi @Hello-Helo ! Thank you for opening this issue.

I'm unable to reproduce the problem on macOS. I'll work on reproducing using an environment closer to yours.

**Comment by Hello-Helo** [comment]
Hello again! It has been a while and this bug stopped happening. Maybe some conflict caused it, but now there is no way to know. Thank you for the attention!

**Comment by reobin** [comment]
Thank you for the update @Hello-Helo !
