### ISSUE TITLE
Can't Change Typewritten Symbol

### ISSUE THREAD

**Issue by avishekdutta531** [reobin/typewritten#120]
![Screenshot from 2021-08-27 11-11-05](https://user-images.githubusercontent.com/74361331/131075230-e698204f-2c6e-4dfc-a3f0-c14e7f6193d7.png)

I can't change the symbol

**Comment by reobin** [comment]
Hi @avishekdutta531 !

I'm so sorry for this delay. I've been very busy with personal stuff.

Thank you for reaching out. Is this still a problem for you?

If so, try to define the `TYPEWRITTEN_` variables _before_ the `fpath`, `autoload`, and `prompt` lines
