### ISSUE TITLE
How to uninstall typewritten?

### ISSUE THREAD

**Issue by always4113** [reobin/typewritten#129]
**Uninstall typewritten**

I don't know how to uninstall this.
please help me..!!
I want to delete it completely, not just deactivate it. 🤔

**Comment by reobin** [comment]
Hi @always4113 ! May I ask how you installed it?

**Comment by always4113** [comment]
I used npm to install it :)

**Comment by reobin** [comment]
Were you able to uninstall the prompt, @always4113 ? If so, do close the issue. Thanks!
