### ISSUE TITLE
add a prefix for the righthand side

### ISSUE THREAD

**Issue by xenoterracide** [reobin/typewritten#13]
So this theme is basically exactly what I was looking for, however I do have one thing I'd like to configure, when I copy and paste code from my terminal, I'd like the code to be basically executable, or show what I executed.

```
> ls .         service-graph -> feature/RS2-1003 $
```
so that last part isn't part of the output or what was executed, what I'd like is for that to read as

```
> ls .         # service-graph -> feature/RS2-1003 $
```

so it reads and acts as a comment if someone copy's and pastes

**Comment by reobin** [comment]
So what I understand is that you would like the `#` character to be displayed at all times? Should be a pretty easy option to implement if the need is valid!

**Comment by xenoterracide** [comment]
yes, and yeah I figured this would be. It's all about me copy and pasting into everthing from emails, discord and stackoverflow

**Comment by reobin** [comment]
Sorry for the wait @xenoterracide !
An option called `TYPEWRITTEN_RIGHT_PROMPT_PREFIX` was added. See the readme for your specific use case. I will keep thinking about how #14 can be done simply this week.
Thank you!

**Comment by reobin** [comment]
@all-contributors please add @xenoterracide for ideas
