### ISSUE TITLE
Typewritten or Oh-my-zsh?

### ISSUE THREAD

**Issue by c-fitzmaurice** [reobin/typewritten#137]
Hey all, thanks for a fantastic prompt, just trying to track something down.

When I misspell a command, the prompt displays `127` before the caret...is this coming from Typewritten or should I be looking elsewhere in my config?

Thanks!

<img width="216" alt="image" src="https://user-images.githubusercontent.com/3401771/159142959-ab5e6cae-5a45-4d86-89c5-2fa12b4c336c.png">

**Comment by reobin** [comment]
Hey @c-fitzmaurice !

Just in case you didn't find your answer. That's the return code coming from `zsh` when a command fails. Its purpose is to identify the error that occured in the last command.

`typewritten` displays the return code only when the last command is not succesful (return code = 0)

To disable that display, add the followint config in your `.zshrc`:

```bash
export TYPEWRITTEN_DISABLE_RETURN_CODE=true
```

**Comment by c-fitzmaurice** [comment]
Yes! Thanks I found that just after I opened the comment. Appreciate it!
