### ISSUE TITLE
show path relative to repo/home

### ISSUE THREAD

**Issue by xenoterracide** [reobin/typewritten#14]
so... I thought that *mh* was doing what I'm about to ask for, turns out... it's just truncating and the path I had was the perfect number of characters... I don't really know how feasible this really is...

this is what *mh* was showing...
```
[calebcushing:.../aurelia/packages/__tests__]$     (topic/proxy✱)
```

what I thought this was saying was the root of the git is the `aurelia` directory, and I'm in `aurelia/path/to`, and I thought it was saying that I could use `...` to get there.

so what would be useful, because I definitely have more than one project with the same standard structure, directory/filenames, so what would be useful, maybe is showing the git root directory name.

maybe like this

```
>               # aurelia/.../__tests__ -> topic/proxy $ +
```

and if you're not in a repo

```
>               # ~/.../__tests__
```

**Comment by reobin** [comment]
Hi @xenoterracide !

This sounds really interesting, and I'd like it added as an option, although I might not be able to do it fast as I am pretty busy this week.

I am going to do some tests today and see what I can do.

**Comment by reobin** [comment]
@xenoterracide 
Finally got arround to work on this a little. Pull `master` and add this line to your `.zshrc` to use the feature:
```shell
export TYPEWRITTEN_GIT_RELATIVE_PATH=true
```
This will display the git root directory as well as the current working directory when you're inside a git repo.
Tell me what you think about it!

**Comment by xenoterracide** [comment]
so cool dude, these are awesome, thanks!

**Comment by reobin** [comment]
Ended up trying the theme like this and I am liking it a lot.
Maybe this should be a default in the future! We'll see
Thanks for the suggestion!
