### ISSUE TITLE
TYPEWRITTEN_SYMBOL and TYPEWRITTEN_ARROW_SYMBOL are not working.

### ISSUE THREAD

**Issue by CrisDgrnu** [reobin/typewritten#145]
**Describe the bug**
TYPEWRITTEN_SYMBOL and TYPEWRITTEN_ARROW_SYMBOL are not working. I'm trying to change the default icons, but the properties don't seem to work.

**To Reproduce**
1. Install the theme (using zsh and oh-my-zsh on ubuntu with gnome-terminal)
2.  Add these lines to the end of.zshrc 
```
export TYPEWRITTEN_PROMPT_LAYOUT="pure"
export TYPEWRITTEN_ARROW_SYMBOL="=>"
export TYPEWRITTEN_SYMBOL="&>"
```
3. Close and open the terminal

**Expected behavior**
The icons should be changed

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Shell: ZSH with Oh-My-Zsh
 - Terminal emulator: gnome-terminal

**Comment by reobin** [comment]
Hello @CrisDgrnu, thank you for reaching out!

Make sure to add the configuration lines _before_ the line that calls the prompt to be used.

Example of my config:
```sh
export TYPEWRITTEN_RELATIVE_PATH="home"
export TYPEWRITTEN_PROMPT_LAYOUT="pure"

autoload -U promptinit; promptinit
prompt typewritten
```

If you are using `oh-my-zsh`, make sure to add the lines before the line sourcing `oh-my-zsh`:
```sh
export TYPEWRITTEN_RELATIVE_PATH="home"
export TYPEWRITTEN_PROMPT_LAYOUT="pure"

source $ZSH/oh-my-zsh.sh
```

Let me know if that helps out!

**Comment by CrisDgrnu** [comment]
Yep, the problem was that I was writting the exports after the source command, thanks!
