### ISSUE TITLE
arrow at cursor breaks on incorrect bash command

### ISSUE THREAD

**Issue by vishalmamidi** [reobin/typewritten#147]
**Describe the bug**
If there is an error in shell command arrow mark breaks and shows runmber before arrow mark,
`>` changes to `127 >` 
to fix that I have to do clear command or invoke zsh shell again.

**To Reproduce**
type incorrect command "safdasfdasfa" 

**Expected behavior**
*127* numbers should not appear infont of arrow.

**Screenshots**

![image](https://user-images.githubusercontent.com/12382861/184410814-933223ea-b15d-461e-95e7-96d313187ebd.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 
 - Version 22

**Smartphone (please complete the following information):**
 - Device: [e.g. rog phone 2]
 - OS: android 11
 - Browser chrome

**Comment by ndom91** [comment]
This is the expected behavior. `127` is the exit code for `command not found`.

**Comment by reobin** [comment]
Hello @vishalmamidi ! thank you for reaching out.

@ndom91 is right, this is the expected behavior. In the documentation, you can find the following line to help you out:
> The return code display can be disabled by setting `TYPEWRITTEN_DISABLE_RETURN_CODE` to `true` in your `.zshrc`
