### ISSUE TITLE
Timestamp on prompt

### ISSUE THREAD

**Issue by santiago-br** [reobin/typewritten#148]
Hi,

Is it possible to append a timestamp on the prompt? It would be helpful to know when a command was run.

I've tried with `TYPEWRITTEN_RIGHT_PROMPT_PREFIX`, but it seems it is only read on start, so `date` doesn't work :(

**Comment by reobin** [comment]
Hi @santiago-br ! Thanks for reaching out

Evaluating the right prompt on every command is actually a great idea. I'll make sure to work on this. (I also highly encourage anyone reading this to send a PR 🌞)

Also, I like the idea of an actual timestamp option. I'll think it over

**Comment by KEDLogic** [comment]
I'd like to add on to this: I'm needed additional information added my prompt (Kube context for example, but its dynamic depending on the host system).

The TYPEWRITTEN_RIGHT_PROMPT_PREFIX seem a solid enough location if it was evaluated every command. I'll be watching for an update on this. :)

**Comment by KEDLogic** [comment]
I added a kube_context prompt addition for my own purposes. Will fork and use that for now.

**Comment by reobin** [comment]
Discussion following in #149

**Comment by reobin** [comment]
Hey @santiago-br ! Happy to announce that the last update introduced the `TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION` option which would let you add a timestamp as the right prompt prefix.

Example:
```sh
export TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION=(date +%H:%M:%S)
```
