### ISSUE TITLE
conda environments use the wrong environmental variable

### ISSUE THREAD

**Issue by accelyte** [reobin/typewritten#154]
**Describe the bug**
See title, the same bug is mentioned here: https://github.com/romkatv/powerlevel10k/issues/762
When a conda environment is activated (in my case, through Miniforge), typewritten uses `$CONDA_PREFIX`
https://github.com/reobin/typewritten/blob/69b3fad6061bfedb62063615ef52663d76182790/typewritten.zsh#L56-L57

On the base environment, this is what I get:
```
CONDA_PREFIX=/home/username/.miniforge3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base)
```

On environment `test`, this is what I get:
```
CONDA_PREFIX=/home/username/.miniforge3/envs/test
CONDA_DEFAULT_ENV=test
CONDA_PROMPT_MODIFIER=(test)
CONDA_PREFIX_1=/home/username/.miniforge3
```

On the base environment, the prefix becomes `(.miniforge)` instead of `(base)`, whereas on environment `test`, the prefix is correctly shown as `(test)`.

typewritten should use either `CONDA_DEFAULT_ENV` or `CONDA_PROMPT_MODIFIER` instead of `CONDA_PREFIX` to indicate the current conda environment.

**To Reproduce**
1. Install Miniforge with `conda init`
2. Restart shell
3. See that the prefix is wrong

**Comment by reobin** [comment]
Hi @accelyte !

Thanks for reaching out.

`CONDA_PROMPT_MODIFIER` seems like exactly what we are looking for here.

I will create a pull request for this.

**Comment by reobin** [comment]
@accelyte An update has been released. v1.5.1 includes this change. Thanks again!
