### ISSUE TITLE
On commit, the cursor overwrites the the arrow on the left.

### ISSUE THREAD

**Issue by mrillusi0n** [reobin/typewritten#18]
### Before Push
Weird behavior of the prompt.
![image](https://user-images.githubusercontent.com/37063502/81806488-2931e900-953a-11ea-8fa1-9bb0d24b3632.png)

### After Push
Prompt restores. You can see that `gp` was written over the arrow.
![image](https://user-images.githubusercontent.com/37063502/81806635-5da5a500-953a-11ea-9567-eea1e9fe9068.png)

**Comment by reobin** [comment]
Hi @mrillusi0n !

That is weird indeed.

What do you use to commit? vim? I am thinking maybe the cursor fix function could be guilty here.

Also, did the problem start happening after recent  updates of typewritten?

**Comment by mrillusi0n** [comment]
`gp` is aliased to `git push -u origin master`. I have tried with and without calling the `_fix_cursor`. Currently, it's just
```bash
precmd_functions=(_set_right_prompt)
```
Here's one with it enabled:
![image](https://user-images.githubusercontent.com/37063502/81830654-fd266000-9559-11ea-97c5-073baaf93559.png)
The arrow is still over written when I have an unpushed commit.

**Comment by reobin** [comment]
Thank you for testing without `_fix_cursor` @mrillusi0n . That is curious, and I am unable to reproduce the bug. Could you try pulling master, sourcing `.zshrc` or ending you zsh session completely?

I notice that there is a blank space at the right of your right prompt when the prompt is absent. That's my only hint. I will keep looking into that when I have some time.

**Comment by mrillusi0n** [comment]
Spaces on the right also appear when I use ➤ as the `prompt_symbol`.
![image](https://user-images.githubusercontent.com/37063502/81844378-9eb6ad00-956c-11ea-9276-45d288e70b7f.png)

I think this is silly, but what I've done is — copy all the contents from `typewritten.zsh-theme` on the repo, and paste it in `~/.oh-my-zsh/custom/themes/typewritten.zsh-theme`. Could that be something that's causing the problem?

I'm sure I've copied the latest version of `typewritten.zsh-theme` from the repo.

**Comment by reobin** [comment]
I'll do some tests with your prompt symbol. It could lead to the problem. Thanks!

**Comment by reobin** [comment]
@mrillusi0n 

Tried your symbol and setup with your files and still nothing... What terminal are you using?

<img width="586" alt="Screen Shot 2020-05-13 at 17 18 09" src="https://user-images.githubusercontent.com/5920450/81866916-ea9e2d80-953d-11ea-951f-0182921ba05c.png">

**Comment by mrillusi0n** [comment]
Alacritty. I just checked on other terminals, the problem does not exist. But I remember seeing the same problem happen on Cool Retro Term.

**Comment by reobin** [comment]
Just tried alacritty and the problem doesn't happen for me. Super confusing.

So it doesn't happen for you when you use iTerm2 or other terminals?

**Comment by mrillusi0n** [comment]
![image](https://user-images.githubusercontent.com/37063502/81872008-91161d00-9596-11ea-8a96-df494ca53985.png)

This is interesting. Only Alacritty is having the problem. But I do remember I had faced the problem on CRT. And somehow it's managed to not break on CRT this time.

**Comment by mrillusi0n** [comment]
I have no clue. I ran Alacritty with the default config.

![image](https://user-images.githubusercontent.com/37063502/81873480-7c875400-9599-11ea-900a-70986410ebd0.png)

No luck :\

**Comment by reobin** [comment]
Well, sadly I can't reproduce it, I'm no help. I will try again these days.
Feel free to play in the code, turning off stuff, etc. and see if something comes up.
I'm really curious about this

**Comment by mrillusi0n** [comment]
![image](https://user-images.githubusercontent.com/37063502/81923740-c3a63100-95fb-11ea-8205-c2f9032ac5d3.png)

This is Kitty, another GPU-based Terminal, having the same problem.

**Comment by reobin** [comment]
What is the git status of this repo? Could it be a certain character messing up?
You could try changing the defined characters for the different git statuses and see what happens

**Comment by reobin** [comment]
Try commenting out the `local git_info` variable and see if the problem is with the git stuff

**Comment by mrillusi0n** [comment]
No luck. It's messing up. But I did see that Alacritty and Kitty, both being GPU based Terminal Emulators, have the same behavior (spaces on the right, overwriting the prompt symbol...).

**Comment by mrillusi0n** [comment]
My next move is to find another GPU based terminal and see if that faces the same problem, haha.

**Comment by mrillusi0n** [comment]
Update: I cloned the Alacritty repo and built it on my system. Seems to work fine so far.

![image](https://user-images.githubusercontent.com/37063502/82028921-d8de9680-96b3-11ea-92e5-54b8a6cdacc3.png)

Although, I'm not sure about Kitty, might as well do the same and try, or maybe not.

**Comment by reobin** [comment]
Thank you for doing all this research @mrillusi0n although we didn’t anything significant. 

Let’s keep an eye out for anyone else having similar problems
