### ISSUE TITLE
I'd like to have the freedom of customizing my cursor, but the theme forces it to be an underline.

### ISSUE THREAD

**Issue by mrillusi0n** [reobin/typewritten#2]
I'm using iTerm2, and saw that changing the cursor type in the terminal settings won't have an effect, when I have this theme enabled.

**Comment by quizzicaltrains** [comment]
I had that issue too, I solved it by commenting out the last line so that `precmd_functions+=(_fix_cursor)` becomes `# precmd_functions+=(_fix_cursor)`.

**Comment by mrillusi0n** [comment]
It'd be nicer if the user is given a choice. @quizzicaltrains, thank you!

**Comment by reobin** [comment]
Thank you for the answer @quizzicaltrains !

The reason I have this piece of code is that exiting vim editor with zsh always sets the cursor as a box, no matter your terminal configuration. This forces the cursor back to an underline every time.

I like the idea of having an option for cursor in the `.zshrc` file. I will look into it soon enough.

**Comment by reobin** [comment]
@mrillusi0n @quizzicaltrains an option was added to customize the cursor! See how in the merge request #3

**Comment by reobin** [comment]
@all-contributors please add @mrillusi0n for idea
