### ISSUE TITLE
How to add padding to the windows

### ISSUE THREAD

**Issue by n-e-o-n-7** [reobin/typewritten#24]
How to add padding to the windows
That's so beautiful

**Comment by reobin** [comment]
Hi @n-e-o-n-7 !

If you’re using iTerm2, see [this comment](https://github.com/reobin/typewritten/issues/12#issuecomment-619558924) I made on an old issue.

If you’re using something else, look it up, there are options for padding (sometimes called margin) on pretty much all terminals.
