### ISSUE TITLE
Usage with Antibody

### ISSUE THREAD

**Issue by jletey** [reobin/typewritten#26]
**Is your feature request related to a problem? Please describe.**

I have a list of all my Zsh plugins (including `typewritten`):

```sh
# ~/.dotfiles/zsh/plugins.txt

zsh-users/zsh-autosuggestions branch:develop
zsh-users/zsh-syntax-highlighting
#mafredri/zsh-async
#sindresorhus/pure
reobin/typewritten
```

In my Zsh config, I have the following:

```sh
# ~/.zshrc

source <(antibody init)
antibody bundle < ~/.dotfiles/zsh/plugins.txt

source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/alias.zsh
```

However, I get the following (an unstyled prompt):

<img width="1252" alt="Screenshot 2020-06-04 at 09 58 19" src="https://user-images.githubusercontent.com/62398724/83736709-f024fa00-a649-11ea-8b35-6cd76217feb6.png">

**Describe the solution you'd like**

I would like to be able to use `typewritten` with [Antibody](https://getantibody.github.io/).

**Describe alternatives you've considered**

I guess I could switch my entire setup over to oh-my-zsh, but I don't want to do that just for a prompt theme.

**Additional context**

N/A

**Comment by reobin** [comment]
Hi @jletey !
Thank you for the suggestion.

I have not heard of antibody but making typewritten standalone (no zsh or oh-my-zsh) is something I have had in mind for a while.

From what I understand, your request would remove oh-my-zsh as a dependency, and it is a step in the right direction for me.

Could you link to some themes that do support antibody?

**Comment by jletey** [comment]
@reobin Awesome really glad to hear this!

The only other theme that I’ve used with Antibody, is [pure](https://github.com/sindresorhus/pure#antibody). But I’m sure there are many others out there :)

**Comment by jletey** [comment]
@reobin More than happy to take a look at this! I'll let you know what I find :)

**Comment by reobin** [comment]
@jletey 

So I created a branch called feat/zsh-bundle, where I created a file `typewritten.zsh` which is still WIP (missing features), but works without oh-my-zsh.

Only thing missing for this new file to work with a package manager is the `typewritten.plugin.zsh` file which is also a symlink to the theme. Shouldn't be a problem whatsoever.

I added the manual instructions for now to install the `oh-my-zsh`less theme. I think we can start building on that to add the features missing. I don't have more time for today to work on it but this is what is missing: 
- colors
- git status indicator
- maybe export each feature in its own file to keep the main file cleaner

Tell me if what you find makes sense with what I've done so far. And maybe help me run some tests with antibody, as I don't use it 😅 (after adding the `typewritten.plugin.zsh` symlink file)

Later!

**Comment by reobin** [comment]
So I couldn't help myself, and kept working 😅 It wasn't that much work actually!

Got to implement all the features old typewritten had. And now it doesn't need oh-my-zsh, which is great.

As I said, I added the instructions on [how to manually install the theme.](https://github.com/reobin/typewritten/tree/feat/zsh-bundle#manual). I'd like to have another opinion on this, and a check if it actually works.

Also, I'll need some help writing the instructions on how to install it with a package manager, if it works. If it doesn't, we can identify what is wrong.

**Comment by jletey** [comment]
> I'd like to have another opinion on this, and a check if it actually works.

@reobin Thx so much for working on this 🙏 

<img width="1252" alt="Screenshot 2020-06-09 at 08 30 50" src="https://user-images.githubusercontent.com/62398724/84118962-a19da400-aa2b-11ea-8e43-1181cc67a2fb.png">

The only thing that is missing is the directory 🤔

Other than that it works amazing 😍

**Comment by jletey** [comment]
> Also, I'll need some help writing the instructions on how to install it with a package manager, if it works. If it doesn't, we can identify what is wrong.

@reobin When using the latest code with Antibody, it unfortunately doesn't work :/

```sh
# ~/.dotfiles/zsh/plugins.txt

zsh-users/zsh-autosuggestions branch:develop
zsh-users/zsh-syntax-highlighting
#mafredri/zsh-async
#sindresorhus/pure
reobin/typewritten branch:feat/zsh-bundle
```

**Comment by jletey** [comment]
<img width="1252" alt="Screenshot 2020-06-09 at 12 37 05" src="https://user-images.githubusercontent.com/62398724/84144588-65306f00-aa50-11ea-8e93-80d3db085dba.png">

There seems to be a problem with the git part of the prompt

**Comment by reobin** [comment]
Hmm, I'll take a look as the current directory display works fine on my end.

About antibody, did you create the symlink file called `typewritten.plugin.zsh`?

**Comment by jletey** [comment]
> Hmm, I'll take a look as the current directory display works fine on my end.

Alright, thx again for working on this :)

> About antibody, did you create the symlink file called `typewritten.plugin.zsh`?

I'll try that, IMO, I think it's worthwhile to push the symlink to the branch.

**Comment by reobin** [comment]
Current directory part was a dumb mistake 😅 You can pull and it should work.

I now also pushed the symlink plugin file, tell me how that works for you. I'll do some tests too.

Maybe I end up liking antibody.

**Comment by reobin** [comment]
Got it to work with these lines in my `.zshrc`:
```shell
source <(antibody init)
antibody bundle reobin/typewritten branch:feat/zsh-bundle
```
Struggled a little bit at first because I has pulled the master branch, and just specifying another branch later didn't update the local repo pulled by antibody.

**Comment by jletey** [comment]
> and just specifying another branch later didn't update the local repo pulled by antibody.

Haha yep just realised that 😅 I now have it working with Antibody 🎉 I can help submit a PR to add instructions on how to install.

Also, seems as tho there is a hick-up with git rn:

<img width="1252" alt="Screenshot 2020-06-09 at 14 19 01" src="https://user-images.githubusercontent.com/62398724/84152340-67002f80-aa5c-11ea-8c17-5b653b2c6ff0.png">

When I'm in the `~/Desktop/release` dir, the git status shows fine. However when I'm inside `~/Desktop/release/app`, it errors, even tho I'm still in the same git repo.

**Comment by reobin** [comment]
So one of the way the prompt checks for a git repository is to check if the `.git` repository exists.

I will remove this check and just keep the `git rev-parse` command. Could you pull and test again?

**Comment by jletey** [comment]
<img width="1252" alt="Screenshot 2020-06-09 at 16 43 48" src="https://user-images.githubusercontent.com/62398724/84169320-683b5780-aa70-11ea-9d71-ba54299e1354.png">

Now it's failing in the git dir and the sub-dir

**Comment by reobin** [comment]
Wow ahah

Are you sure everything is up to date? No check should be done for the `.git` directory.

The code for the `typewritten_is_git_repository` functions looks like this:
```shell
typewritten_is_git_repository() {
  if $(command git rev-parse --git-dir 2> /dev/null); then
    echo true
  else
    echo false
  fi
}
```

**Comment by jletey** [comment]
<img width="1252" alt="Screenshot 2020-06-09 at 17 22 38" src="https://user-images.githubusercontent.com/62398724/84173919-d3d3f380-aa75-11ea-959a-d746b8097024.png">

Yeah it's updated! Still not working. And when I run `cat lib/git.zsh`, the updated code is there:

<img width="1252" alt="Screenshot 2020-06-09 at 17 25 18" src="https://user-images.githubusercontent.com/62398724/84174200-33ca9a00-aa76-11ea-90eb-66fdb46cbc71.png">

**Comment by reobin** [comment]
That is weird. Could you try on another repo?

or run this: `command git rev-parse --git-dir 2> /dev/null` in your repo and see what pops up?

**Comment by reobin** [comment]
Basically, `command git rev-parse --git-dir 2> /dev/null` returns the path of the `.git` directory if you are in a git repo, and returns nothing if not.

**Comment by reobin** [comment]
I updated the condition, maybe it runs better now.

Run `antibody update`. If not, I am puzzled as it works perfectly on my side 🤔

**Comment by jletey** [comment]
> maybe it runs better now.

Wuhuu!!! It works!!! 🎉 Thx for debugging this!



> Run `antibody update`.

Ah I feel stupid 😅 Thx for the tip

**Comment by reobin** [comment]
I'll update the readme, so it's more readable.

When you got a little bit of spacetime, could you come up with the docs on how to install it with various package managers?
I'm thinking of antigen and antibody, but maybe more if it actually works.

I think common ways to install a prompt theme are:
- prezto
- zim
- antigen
- antibody
- zgen
- zplug

You could try a couple, write the docs, and make a PR with the target branch to be `feat/zsh-bundle`.
When we merge, you would show up as a contributor.

I'll help with some package managers, but I want you to show up in the contributor list! 🎉

**Comment by jletey** [comment]
> could you come up with the docs on how to install it with various package managers?

I'd be more than happy too!

> but I want you to show up in the contributor list! 🎉

🤗
