### ISSUE TITLE
Align right prompt

### ISSUE THREAD

**Issue by jletey** [reobin/typewritten#31]
**Is your feature request related to a problem? Please describe.**

When adding/removing files in a git dir, the right prompt varies:

<img width="1252" alt="Screenshot 2020-06-17 at 09 49 11" src="https://user-images.githubusercontent.com/62398724/84877502-814f9400-b080-11ea-8d02-e31689846c8a.png">

It ends up looking unorganised and a bit chaotic in my opinion.

**Describe the solution you'd like**

Align the `->` characters in all the right prompts if that's possible 🤔

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by reobin** [comment]
Hey again @jletey !

Would you suggest some padding on the right to make status fit at all times, that would look funny when there is no status change, although it could be an option.

The other possibility would be to move the status symbols somewhere else. Maybe an option to reverse the right prompt like `? ! master <- typewritten`.

Did you have another idea to achieve a more aligned look on all lines?

**Comment by jletey** [comment]
Hmm I agree, padding would look weird. But so would the reverse IMO.

I don't know the best way to go about doing this 🤔 This is the first prompt with a RPROMPT that I've ever used 😅

**Comment by reobin** [comment]
We could explore other prompt layouts completely. I guess that could be fun.

Let's think about some options that would look aligned at all times unless you change directory:
```shell
# 1

❯ _                     ! ? master -> typewritten
```
```shell
# 2

❯ _                     ! ? master <- typewritten
```
```shell
# 3
# In this one the branch will move, but not the arrow

❯ _                     master ! ? -> typewritten
```
```shell
# 4
# I think this one is my favorite

master ! ? 
❯ _                                   typewritten
```
```shell
# 5
# This one I wouldn't make it a default since a lot of
# prompts out there have this layout, but it could
# definitely be an option

typewritten -> master ! ? 
❯ _
```

What do you think? Any other idea in mind?

**Comment by reobin** [comment]
Other things than arrows could be displayed too, like parenthesis or something:
```shell
# 6

❯ _                     (master ! ?) typewritten
```

**Comment by jletey** [comment]
Hmm I'm a fan of `3` and `4`. However in my head, in option `3`, it doesn't make sense to have the git status before the dir.

For `4` it's pretty much similar to Pure tbh, but it's my favourite option.

**Comment by reobin** [comment]
Should be pretty easily done. I'm think of using the `TYPEWRITTEN_PROMPT_LAYOUT` variable for this, although it was used in the past for user and host stuff. What do you think?

Also, what names could we use for them?
Right now, we have `singleline`, `singleline_verbose`, and `multiline`, but like I said, they are used for `user@host` stuff.

**Comment by jletey** [comment]
Sounds good to me! Sorry for the late reply 😬

**Comment by reobin** [comment]
I created a branch #34 you can try it out for now and tell me what you think about it!

I am also working on an async option for typewritten, which should be in the next week or so
