### ISSUE TITLE
feat: Implement color option for all the prompt parts

### ISSUE THREAD

**Issue by eleven4y** [reobin/typewritten#39]
Add flag for select color of return code, may be from list available colors

I suggest leaving red by default and create list of supported colors

**Comment by reobin** [comment]
I have thought about various options for colors, not just the return code.

Different colors could be chosen for everything (the blue symbol, the purple git status, etc.)

I have not worked on it yet, so I have yet to figure out a good readable way to do this.
I will have a go at it soon enough though!

**Comment by eleven4y** [comment]
Good, may be i will think about it solution too

**Comment by reobin** [comment]
Color options were implemented in [v1.2.0](https://github.com/reobin/typewritten/releases/tag/v.1.2.0).

See the docs on how to configure [here](https://github.com/reobin/typewritten/wiki/Prompt-color-customization)
