### ISSUE TITLE
bug: red prompt symbol after errors with TYPEWRITTEN_DISABLE_RETURN_CODE 

### ISSUE THREAD

**Issue by eleven4y** [reobin/typewritten#41]
**Describe the bug**

**To Reproduce**
1. Go to 'terminal'
2. Enter a fake command, for example 'fake_command'
3. Press enter

**Actual behavior **
Color of prompt symbol is red.

**Expected behavior**
Color of prompt symbol the same, as on prev line.

**Screenshots**
<img width="585" alt="Screen Shot 2020-07-21 at 5 37 33 PM" src="https://user-images.githubusercontent.com/51177852/88068444-df3c3380-cb78-11ea-8aa8-a36bcee67d15.png">

**Comment by reobin** [comment]
I thought this was intentional!

But yeah, it would make sense to have the prompt 100% not affected by the return code if the return code display is disabled.
