### ISSUE TITLE
wiki: typo in installation for oh-my-zsh

### ISSUE THREAD

**Issue by zembrowski** [reobin/typewritten#45]
Hey there,

seems there's a typo in the installation [wiki](https://github.com/reobin/typewritten/wiki/Installation) for oh-my-zsh. Please consider changing:

`ls -s "$ZSH_CUSTOM/themes/typewritten/async.zsh" "$ZSH_CUSTOM/themes/async"`

to

`ln -s "$ZSH_CUSTOM/themes/typewritten/async.zsh" "$ZSH_CUSTOM/themes/async"`

**Comment by reobin** [comment]
@zembrowski Good catch, thanks!

**Comment by Ivan-Velickovic** [comment]
For me at least, the typo is still there when I visit the site.

**Comment by reobin** [comment]
I have had an update in mind for typewritten.dev for a while but didn't quite have the time to do it. I'll at least update the content for now so that it's on par with the wiki.

Thanks @Ivan-Velickovic

**Comment by Ivan-Velickovic** [comment]
Ah no worries just thought I'd let you know in case you didn't know for some reason :))

**Comment by reobin** [comment]
@all-contributors please add @zembrowski for doc

**Comment by reobin** [comment]
@all-contributors please add @Ivan-Velickovic for doc
