### ISSUE TITLE
24 bit colors

### ISSUE THREAD

**Issue by barischrooneyj** [reobin/typewritten#46]
**Is your feature request related to a problem? Please describe.**
I use a color theme for emacs and tmux, this theme is Dracula. I would like to set typewritten colors that match this theme.

**Describe the solution you'd like**
This would be possible if I could set any 24 bit color code instead of only one of the ANSI colors.

**Additional context**
The image below shows the colors I use with tmux, I would like the typewritten prompt and current directory to also use colors directly from the Dracula theme, to match the rest of the colors.

<img width="1280" alt="Screenshot 2020-08-04 at 16 36 42" src="https://user-images.githubusercontent.com/6631452/89313655-b172e680-d670-11ea-9869-2e3c7c4df9b3.png">

**Comment by reobin** [comment]
Hi @barischrooneyj !

Turns out this is definitely possible if your terminal supports true color.
It would technically be possible right now if the regex validating the `TYPEWRITTEN_COLORS` variable wasn't so restrictive.
I'll update this today so that you can create your theme.

Hex color codes will be supported like this:
```bash
export TYPEWRITTEN_COLORS="prompt:#008080;symbol:#682d1e;git_branch:#30bf2d;current_directory:#8ac988"
```

I'm quite happy with how this one turned out, and gives me the idea of creating themes for the prompt! A theme could simply be a preset of color settings. Dracula could be the first one 🚀

**Comment by reobin** [comment]
I'm not normally that fast, but this was a quick fix.

`npm update -g typewritten` (or whatever you had it installed with) 😊

**Comment by reobin** [comment]
@barischrooneyj I just pushed a new version which will make it easier to create themes.

When you're up to date, add this variable to your `.zshrc` and you should have a nice dracula theme going on.
```bash
export TYPEWRITTEN_COLOR_MAPPINGS="primary:#9580FF;secondary:#8AFF80;accent:#FFFF80;info_negative:#FF80BF;info_positive:#8AFF80;info_neutral_1:#FF9580;info_neutral_2:#FFFF80;info_special:#80FFEA"
```

**Comment by barischrooneyj** [comment]
@reobin this looks great! thank you very much!

Perhaps adding some information to the wiki about where the different color components (e.g. info_negative:#FF80BF) are used, would be useful.

Thanks again!

**Comment by reobin** [comment]
I actually [just did that](https://github.com/reobin/typewritten/wiki/Prompt-color-customization)!

Not sure about the readability since there is quite a lot of info on that page. Might separate into sub-pages later.

**Comment by reobin** [comment]
@all-contributors please add @barischrooneyj for ideas
