### ISSUE TITLE
Custom date/time format string

### ISSUE THREAD

**Issue by barischrooneyj** [reobin/typewritten#48]
**Is your feature request related to a problem? Please describe.**
The date format used in the US is different to that used in Europe, the default timestamp shown in the tmux status bar with typewritten uses the US date format (month before day).

**Describe the solution you'd like**
Allowing the user to set something like `export TYPEWRITTEN_DATE_FRMT=%d/%m/%Y, %H:%M:%S` to set a custom date/time string would be fantastic.

**Comment by reobin** [comment]
This is a setting within tmux itself.

Something like this might help you: `set -g status-right "%d/%m/%Y, %H:%M:%S"`

**Comment by barischrooneyj** [comment]
Thank you for your prompt replies @reobin . I am having a little issue with this, if I set `set -g status-right "%a"` before `run '~/.tmux/plugins/tpm/tpm'` then the date format is not modified, however if I set after then typewritten's battery, RAM and CPU indicators get removed.
