### ISSUE TITLE
What is the font file I need to download to make that symbol, whatever it is called, show properly?

### ISSUE THREAD

**Issue by groovitz** [reobin/typewritten#57]
Can you tell me what font family i will need to make it show the proper symbol?

**Comment by reobin** [comment]
What symbol are you talking about?

The font that is used in the demo is [JetBrains Mono](https://www.jetbrains.com/lp/mono/), and most importantly, font ligatures are turned on.

**Comment by groovitz** [comment]
❯ This one. I use JetBrains Mono too. But instead of showing that angled bracket, my prompt just shows an empty rectangle.

**Comment by ben100691** [comment]
> ❯ This one. I use JetBrains Mono too. But instead of showing that angled bracket, my prompt just shows an empty rectangle. Additional note: I use urxvt

Same issue here, rxvt-unicode with Ubuntu Sans. Everything renders perfectly except for the TYPEWRITTEN_SYMBOL which shows as an empty rectangle

**Comment by reobin** [comment]
Are you able to simply paste the symbol and have it shown in the terminal? `❯`
If not, might want to look at how to display such characters in rxvt... I'll take a look myself later today.

In the worst case, you could always change the symbol like this:
```shell
# in .zshrc
export TYPEWRITTEN_SYMBOL=">"
```

**Comment by groovitz** [comment]
That symbol isn't showing in urxvt when I copy paste it. :(

**Comment by reobin** [comment]
Anything new? I had no trouble on Ubuntu. I might have to try an Archlinux distro specifically.

**Comment by groovitz** [comment]
I changed my terminal emulator to alacritty and it works now. I read on forums that urxvt has problems with images and glyphs. So I just changed my emulator.
