### ISSUE TITLE
How to setup like the demo

### ISSUE THREAD

**Issue by yangfanx** [reobin/typewritten#80]
Sorry, if this is not the right place to ask.

I am setting up a new laptop. Found this amazing zsh theme.

But after I install iTerm, oh-my-zsh and typewritten, the iTerm zsh theme is still the default theme.

Is there further instructions to setup like the demo in https://typewritten.dev/#/.

Thanks!

**Comment by reobin** [comment]
Hi @yangfanx !

Is typewritten set as your zsh theme in your `.zshrc` file? If so, did you reload `zsh`?

**Comment by yangfanx** [comment]
I found a useful setup. Issue is closed. Thanks!
