### ISSUE TITLE
TYPEWRITTEN_DISABLE_RETURN_CODE still shows error

### ISSUE THREAD

**Issue by crepppy** [reobin/typewritten#81]
**Describe the bug**
When setting the `TYPEWRITTEN_DISABLE_RETURN_CODE` to true in the `.zshrc` config, the error code of the last command still appears before the prompt

The error seems to be in the commit 31163076e2d5251e7b19e13786ad3ddf3da32afa as the variable names were refactored (presumably with a regex) which caused the variable to change name (`TYPEWRITTEN_DISABLEtw_RETURN_CODE`). Even when setting this new variable to true, the error code is successfully removed, but the prompt looses its coloring.

[The problematic line](https://github.com/reobin/typewritten/commit/31163076e2d5251e7b19e13786ad3ddf3da32afa#diff-03dddf4b85aad1e759facf7cd1874fe5R31)

**To Reproduce**
1. Clone the current master branch
2. Set typewritten as your oh-my-zsh theme
3. Set the variable `TYPEWRITTEN_DISABLE_RETURN_CODE` in your `.zshrc`
4. Open a new terminal and type an erroneous command

**Expected behavior**
The error code returned by the previous command to not be shown before the prompt

**Screenshots**
Setting `TYPEWRITTEN_DISABLE_RETURN_CODE` to true
![image](https://user-images.githubusercontent.com/38158363/93689370-e70b4c00-fac5-11ea-8a19-8325b26bd5c6.png)

Setting `TYPEWRITTEN_DISABLEtw_RETURN_CODE` to true
![image](https://user-images.githubusercontent.com/38158363/93689415-410c1180-fac6-11ea-8cdd-def3b6e3a794.png)
Observe the image above does not have color

**Additional context**
This hasn't been tested using typewritten as a normal prompt but is assumed to be the same as the same script is used

**Comment by crepppy** [comment]
#82

**Comment by reobin** [comment]
Hi @crepppy !

Thanks for the PR. 🎉

Pretty embarrassing lack of QA on my part 😅
I'll do a quick test with typewritten as a zsh prompt, but you are right that it should be the same.

**Comment by reobin** [comment]
Fixed by #82
