### ISSUE TITLE
Async not providing git info

### ISSUE THREAD

**Issue by aaroncaito** [reobin/typewritten#92]
**Describe the bug**
Followed ZSH install instructions, configuration and other items work, git status is not displayed. It's tough to troubleshoot async behavior.

**To Reproduce**
1. Follow install instructions
2. Open terminal with iterm2 on osx
3. no git output

**Expected behavior**
Expect the git status to be displayed

**Screenshots**
![Screen Shot 2020-11-01 at 12 00 06 PM](https://user-images.githubusercontent.com/354400/97809253-d825c680-1c39-11eb-89da-1672d8300c8d.png)

**Desktop (please complete the following information):**
macos 10.15.7

**Additional context**

relevant zshrc:

```
export PATH=$HOME/bin:$HOME/.local/bin:$HOME/go/bin:$HOME/bin:/usr/local/bin:$PATH

export ZSH="/Users/acaito/.oh-my-zsh"

export TYPEWRITTEN_RIGHT_PROMPT_PREFIX="# "
export TYPEWRITTEN_PROMPT_LAYOUT="pure"
export TYPEWRITTEN_GIT_RELATIVE_PATH="true"

ZSH_THEME="typewritten"
#ZSH_THEME_RANDOM_CANDIDATES=( "typewritten" "fishbone++" "spaceship" )

plugins=(git z)

# User configuration
#eval $(thefuck --alias)
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
# alias awsume=". awsume"

fpath=(~/.awsume/zsh-autocomplete/ $fpath)
source $ZSH/oh-my-zsh.sh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform
```

I'm not receiving any error output in terminal.

**Comment by reobin** [comment]
Hey @aaroncaito ! Thanks for the report

There doesn't seem to be anything wrong with your configuration from what I can see.

Some things I would check are:
- What does `git symbolic-ref --short -q HEAD` display when you run it in the repo? That's what typewritten uses to display the branch, for example.
- What's the content of `$ZSH/custom/themes/`? Are both `async` and `typewritten.zsh-theme` present as symlinks?

If both these things are right, we'll keep looking at what seems to not play well with typewritten in your config.

Also, I haven't used the `pure` layout in a while. There seems to be a bug where the last line of the command output is erased on every command, which is quite annoying 😅 

I'll check that out as soon as I can.

**Comment by reobin** [comment]
Hello @aaroncaito! Are you still having the problem? Or have you given up?

The issue I mentioned above is fixed, but for this one, without more context, there is very few things I can do.

Thanks!
