### ISSUE TITLE
Overwriting lines of the previous output

### ISSUE THREAD

**Issue by gartunius** [reobin/typewritten#93]
**Description:**
When using the "pure" prompt layout, sometimes when the command finishes to run, the prompt is placed some lines up from where it should have been placed, causing the previous output to be replaced.

**To Reproduce:**
1.Just do a normal 'oh.my.zsh' installation
2.Install 'typewritten' using the 'oh my zsh' instructions
3.Change the prompt to 'pure' using the command: `export TYPEWRITTEN_PROMPT_LAYOUT="pure"`

I also changed the cursor to 'block' on all my machines, and didn't tested with the normal one.

**Expected behavior:**
Get the full output.

**Screenshots**
![2020-11-02-023250_5846x1080_scrot_cropped](https://user-images.githubusercontent.com/27605237/97835922-021ecd80-1cba-11eb-801a-3c4d01d4b867.png)

**Desktop:**
 - OS: Arch Linux, Ubuntu

**Additional context:**
I was able to reproduce the bug on a Ubuntu machine, and there when I tested 'typewritten' with the original prompt layout('singleline'), there was no problem. Also I didn't attached all the screenshots, because I tested on 2 sistems, with 3 different terminal emulators and three zsh themes and the result was the same as the one I gave, only on the typewritten ones with the 'pure' promp layout had the problem, on all the others there was no promblem. I have all of the screenshots and can upload if anyone wants.

Also tested on the other "multiline" ones and the problem happens on all of them. I only tested the other multiline prompts on my Arch machine by the way.

Also, here's my .zshrc:
```
##
## ZSH Config File
##

# Path to your oh-my-zsh installation.
export ZSH="/home/chomuske/.oh-my-zsh"

export TYPEWRITTEN_PROMPT_LAYOUT="pure"
export TYPEWRITTEN_CURSOR="block"
export TYPEWRITTEN_COLORS="symbol:#fb4934;symbol_error:#cc241d;error_code:#cc241d;git_branch:#83a598;current_directory:#83a598;arrow:#fbf1c7;user:#8ec07c;host_user_connector:#fbf1c7;host:fe8019;prompt:f9f5d7;virtual_env:#f1bd2f;git_rebasing:#d3869b;git_status_staged:#b16286;git_status_new:#fe8019;git_status_modified:#d65d0e;git_status_renamed:#ebdbb2;#git_status_deleted:#458588;git_status_unmerged:#98971a;git_status_diverged:#fabd2f;git_status_ahead:#689d6a;git_status_behind:#b8bb26;git_status_stash:#928374"
#export TYPEWRITTEN_COLOR_MAPPINGS="primary:red;secondary:#fb4934;accent:black;foreground:black"

ZSH_THEME="typewritten"
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
# CASE_SENSITIVE="true"
# DISABLE_UPDATE_PROMPT="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
# ZSH_CUSTOM=/path/to/new-custom-folder

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

export PAGER="vimpager"
```

Also, sorry if I misspelled anything English is not my mother tongue.

**Comment by reobin** [comment]
Hey @gartunius ! Thank you so much for this issue.

I noticed it yesterday while debugging another issue. I will check it out as soon as possible.

For now, what I know is that it happens when the prompt is reset after the async callback. There might be another way to define the break lines so that it doesn't break when the prompt is reset.

**Comment by reobin** [comment]
Hey @gartunius ! I'm pretty confident #94 fixes the issue, but your feedback will confirm it to me, so if you have a chance to pull the new chances and check it out, it would be very appreciated 🙏\

I will then release the new version to npm.

Thank you again for the report, have a good one!

**Comment by reobin** [comment]
@all-contributors please add @gartunius for bug

**Comment by gartunius** [comment]
I tried reinstalling the prompt several times, through the 'oh my zsh'(also tried to reinstall 'oh my zsh') method, and the issue still happens, I also tried reinstalling on my other Ubuntu machine, and the issue still keeps happening. And just to be 100% sure, I also installed on a clean Arch VM, and tested on a Ubuntu Live CD with 'oh my zsh', and the issue still happend. Btw should I do the installation in a different way? Because I pretty much just copy pasted the instruction from [here](https://typewritten.dev/#/installation?id=oh-my-zsh).

**Comment by reobin** [comment]
That's interesting, I had the same issue and that solved it for me. 

I'll try again using Ubuntu (I'm on macOS) and specifically ohmyzsh.

Which version of zsh and ohmyzsh are you using? I'll do my best.

**Comment by gartunius** [comment]
My zsh version is: zsh 5.8, and I updated 'oh my zsh' on my machines when testing today, so it's the latest.

**Comment by gartunius** [comment]
So I was searching a bit about this problem to see if I could find anything to help, and I came across this [Stack Exchange question](https://unix.stackexchange.com/questions/517025/zsh-clear-scrollback-buffer), which seems to be more or less related to the problem here (also in there the person who answered also linked to a [problem like this one](https://github.com/denysdovhan/spaceship-prompt/issues/676) but on other circustances, in which the solution was to add a '-R' parameter on the 'zle reset-prompt' which acording from what the guy who gave the answer it "-R: redisplay the prompt to avoid old prompts being eaten up", so I just wrote that in the 'typewritten.zsh-theme' file on line 94 and it seems to have solved the problem, I'm still testing though, so maybe if this doesn't solve the problem it helps you to find a answer.

**Comment by reobin** [comment]
Thanks for doing the research @gartunius ! Really appreciate it.

I have also found a bunch of related issues, but nothing clear on what a fix would be.

I find it curious that `reset-prompt` and `.reset-prompt` act differently on my machine, and one works better than the other, but oh well it doesn't seem to be the case on Linux.

Let me know how it goes with the `-R` flag! I'll try it too.

**Comment by gartunius** [comment]
I tested on my Arch and Ubuntu machines, as well on a Ubuntu LiveUsb, and the `-R` flag apparently solved the problem, I also tested on the single line layouts to make sure that they still work, and there was no problem.

About the `reset-prompt` and `.reset-prompt`, I tested the `-R` flag with both of them and there was no difference.

By the way, probably doesn't matter, but just in case, the way that worked was with the `-R` flag like this: `zle -R && zle reset-prompt`

**Comment by reobin** [comment]
Thank you so much @gartunius !

I'll test it out tomorrow and deploy a fix if everything works on macOS as well

**Comment by reobin** [comment]
Looks all good on my end as well. Do you want to open the PR @gartunius ?

I can also do it, but I'd like to give you credit for it :)

**Comment by gartunius** [comment]
Thanks, It's my first time opening a pull request, so if there's anything wrong sorry, I'll try to fix it, but if I take too long or something, then you can just do it.
