### ISSUE TITLE
Showing path relative to home instead of just dir name. 

### ISSUE THREAD

**Issue by Scupake** [reobin/typewritten#98]
**Is your feature request related to a problem? Please describe**:
I have lots of dirs that have similar/same name and it sometimes gets confusing.

**Describe the solution you'd like**:
An option to show the entire path relative to ```~``` unless you're in a git repository.

**Comment by reobin** [comment]
Hey @Scupake !

Thanks for this feature request! It's a good idea. We could add a flag for this feature, and a flag for showing the full path at all times.

I'll try out some implementations this week!

**Comment by Scupake** [comment]
Thanks!

**Comment by reobin** [comment]
Hey @Scupake !

#99 is opened

I hope that's what you were looking for! I personally really like the `adaptive` option, so thanks for the feature request! Many will benefit from it 🌞

If you're up to it, you can test it out. I'll spend the day working with that branch active, and merge it at the end of the day if everything went well.

Cheers!

**Comment by Scupake** [comment]
Yeah, it's exactly what I wanted.
Thanks again!

**Comment by reobin** [comment]
@dependabot please add @Scupake for idea and test

**Comment by reobin** [comment]
@all-contributors please add @Scupake for idea and test
